---
title: "The lawR package"
author: "Biandri Joubert"
date: '2022-07-13'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Heres the package and this is what you can do with it

The lawR package has been developed to make a few functions easier for R users with legal backgrounds in South Africa. I walk you through the package in this post and show you what can be done with it. 

The lawR package does two things: 
- it contains templates for popular South African law journal articles 
- it contains two text based data sets

## The main functions of the lawR package

Anyone that has written an academic article will know this: _it is a pain to convert them into a different style or format once you have already done the initial work_. Another universal truth is that no two law faculties appear to able to agree on where the _italics_ should be or on a universal font, line spacing, margin size or layout. This package aims to facilitate switching between templates but also, and more importantly, getting it right from the start. This should minimize the time that a language or style editor takes to review a document and it also gives the author a sense of certainty that the the correct dots are on the "i" and the "t" is crossed at the correct level. 
 
Everything in this package is done through R and the opensource reference manager Zotero. It is possible to use other reference managers. I will add this at a later stage. However, opensource is the mission for now and for that reason Zotero is used. 

This package was created by a human. If you notice any problems or want to contribute, please get in touch via _github_ or by sending me an email. 

# University templates

_**R Templates for publishing in South African law journals**_  
- Potchefstroom Electronic Law Journal (PER)  
- Stellenbosch Law Review  
- Pretoria University Law Press (PULP)  
- The Journal of Comparative Law in Africa (JCLA)  
- Other will be added and developed  

# A few examples of what you can do!


