---
date: "2019-06-17T23:53:00+01:00"
hideLastModified: true
showInMenu: true
title: About
---

# Hello!
Welcome to _Why learn R? For people with legal backgrounds_ ! This is a resource designed with legal backgrounds in mind. However, if you're here, and can take value from the resources and information shared, you are more than welcome to it! I'll explain below what you can expect from this resource at this stage and what's to come. Its a work in progress, and likely always will be because R is constantly developing, and as I learn and get feedback I add to the resource. To understand what the origins of the resource are, read the "authors why" post on the _Why R_ tab. You can also read stories from members of the community at the same _Why R_ tab. If you want to contribute a _Why R_ story, please follow the following _guidelines_. 

# What you can expect from this resource

## _Visual examples: this is why R, this is what you can do with it_ 
This is just the beginning. There are many more things that you can do. 

## _Resources: use these to learn R or to teach others with legal backgrounds R_

Learning R, especially if its your first time is often overwhelming. In my experience, having a goal to work towards made the journey easier. The resources center containing data sets to learn or teach R and the examples provided showing what you can do are intended to inspire a goal to work towards while moving through the initial "intro to R" stages of learning R. 

## Community contributions: why I learnt R and why I encourage learning R


>This website was created using the skills I have learnt with R. Learning a tool such as R gives you a lot more than the ability to analyse text and numbers

# How to get in touch 

Send me an email at: biandrijoubert@gmail.com. You can also contact me through  [Github](https://github.com/b14-RSA), 
[Twitter](https://twitter.com/biandri) or [LinkedIn](https://www.linkedin.com/in/biandri-joubert-8270763b/?original_referer=https%3A%2F%2Fgithub.com%2F) 

# Licence

All material is available under a [CC-BY 4.0 licence](https://creativecommons.org/licenses/by/4.0/).


## What you can and cannot do with the resource

[CC-BY 4.0 licence](https://creativecommons.org/licenses/by/4.0/) allows you to reuse, remix, transform, and build upon the material but with attribution.
